---
title: "Gerrymandering in Alabama: Analysis Plan"
author: "Samuel Barnard"
date: "`r Sys.Date()`"
output: html_document
editor_options:
  markdown:
    wrap: sentence
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../docs") })
nocite: '@*'
bibliography: "../../software.bib"
---

# Abstract

This is a study of gerrymandering in Alabama.
We will test three methods of shape-based compactness scores, assess representativeness of districts based on prior presidential elections and race. 
We will then extend prior studies by calculating representativeness of the convex hull of district polygons.

## Study Metadata

- `Key words`: Alabama, gerrymandering, compactness, convex hull, political representation
- `Subject`: Social and Behavioral Sciences: Geography: Geographic Information Sciences
- `Date created`: 2025-02-17
- `Date modified`: 2025-02-17
- `Spatial Coverage`: Alabama OSM:[161950](https://www.openstreetmap.org/relation/161950)
- `Spatial Resolution`: Census Block Groups
- `Spatial Reference System`: EPSG:4269 NAD 1983 Geographic Coordinate System
- `Temporal Coverage`: 2020-2024 population and voting data
- `Temporal Resolution`: Decennial census